./Antigua &&
./Argantena.sh &&
./Armenia &&
./Aruba &&
./Afghanistan &&
./Albania &&
./Andorra &&
./Angola.sh &&
./Azerbaijan &&
./Bahamas_Belarus &&
./Bangladesh &&
./Barbradus &&
./Barbradus &&
./Benin &&
./Bolivia &&
./Bulgaria &&
./Burkina_Faso &&
./Cambodia.sh &&
./Cameroon.sh &&
./CapeVerde.sh &&
./Cayman &&
./Chad.sh &&
./Chile.sh &&
./Congo &&
./Cook-Island.sh &&
./Cuba &&
./Czech_Republic &&
./Denimark &&
./Ecuador &&
./Estonia &&
./Ethiopia &&
./Fiji &&
./France
